# Generated by Django 2.0.3 on 2018-09-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sites',
            new_name='users',
        ),
    ]
