# Generated by Django 2.0.1 on 2018-10-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181014_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'users'},
        ),
    ]
