# Generated by Django 2.0.3 on 2018-09-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0002_links_isp_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='input_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
