# Generated by Django 2.0.3 on 2018-10-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0005_auto_20181022_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_value',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='sites',
            new_name='site_id',
        ),
    ]
