# Generated by Django 2.0.3 on 2018-10-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0006_auto_20181029_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='site_id',
            new_name='site',
        ),
    ]
