# Generated by Django 2.0.3 on 2018-11-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0007_auto_20181029_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='area_code',
            new_name='area_codex',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='city',
            new_name='cityx',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='description',
            new_name='descriptionx',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='id',
            new_name='idx',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='ipadd',
            new_name='ipaddx',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='location',
            new_name='locationx',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='name',
            new_name='namex',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='site_code',
            new_name='site_codex',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='tagline',
            new_name='taglinex',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='type',
            new_name='typex',
        ),
    ]
