# Generated by Django 2.0.3 on 2018-11-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0008_auto_20181107_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='area_codex',
            new_name='area_code',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='cityx',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='descriptionx',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='idx',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='ipaddx',
            new_name='ipadd',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='locationx',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='namex',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='site_codex',
            new_name='site_code',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='taglinex',
            new_name='tagline',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='typex',
            new_name='type',
        ),
    ]
