# Generated by Django 2.0.9 on 2019-01-19 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0009_auto_20181107_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='other', max_length=20)),
                ('model', models.CharField(default='unknown', max_length=100)),
                ('name', models.CharField(default='unnamed', max_length=100)),
                ('serial_number', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=1, max_length=1)),
                ('ipadd', models.CharField(max_length=19, null=True)),
                ('os', models.CharField(max_length=300, null=True)),
                ('tagline', models.CharField(max_length=500, null=True)),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='netinfo.sites')),
            ],
            options={
                'verbose_name_plural': 'devices',
            },
        ),
    ]
