# Generated by Django 2.0.9 on 2019-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0010_devices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='site',
            new_name='placement',
        ),
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
