# Generated by Django 2.0.9 on 2019-01-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0012_auto_20190121_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
