# Generated by Django 2.0.9 on 2019-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0013_auto_20190121_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='type',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
